services:
    ###> webapp ###
    webapp:
        container_name: app-symfony-production
        # image: 
        ports:
            - 80:80
            # - 443:443
            # - 443:443/udp
        env_file:
            - .env
        environment:
            - APP_ENV=prod
        volumes:
            - .env:/app/.env
        networks:
            custom_network:
                ipv4_address: 172.20.0.10
    ###< webapp ###

networks:
  custom_network:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24  # Définir la plage d'adresses IP